name: Node JS CICD Pipeline
on:
  push:
    branches:
      - master
jobs:
  build_nodejs_app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Set Up Node.js 22
        uses: actions/setup-node@v4
        with: 
          node-version: "22"

      - name: Install Dependencies
        run: npm install

      - name: Build Application     
        run: echo "building application"

      - name: Run ESlint
        run: echo "running eslint"

      - name: Run Unit Test
        run: echo "Running Unit Test" 

        # deploy using docker

      - name: setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t my-nodejs-app .

      - name: tag Docker Images
        run: docker tag my-nodejs-app:latest docknjila/my-nodejs-app:latest

      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{scerets.DOCKER_HUB_USERNAME}}
          password: ${{scerets.DOCKER_HUB_PASSWORD}}  

      - name: Push Docker Image to Docker Hub
         run: docker push ${{scerets.DOCKER_HUB_USERNAME}}/my-nodejs-app:latest
         
          